### ISSUE TITLE
How do I modify user metadata?

### ISSUE THREAD

**Issue by krazyjakee** [colyseus/colyseus-social#14]
I would like to work with custom attributes on the user object. How can I do this?

**Comment by endel** [comment]
Hi @krazyjakee, currently you can do this only via the MongoDb operators, like:

**setting / replacing data**

```
user.updateOne({
  $set: {
    'metadata.coins': 10
  }
});
```

**incrementing / decrementing data**

```
user.updateOne({
  $inc: {
    'metadata.coins': -10
    'metadata.trophies': 5
  }
});
```

Hope this helps!

**Comment by krazyjakee** [comment]
Thanks!
